version: '3.3'

services:
  lower-austria-fire-brigade-incident-mining:
    image: lower-austria-fire-brigade-incident-mining-client
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - "mongo"
    environment:
      MONGO_HOST: localhost
      MONGO_USER: root
      MONGO_PASSWORD: example
      MONGO_PORT: 27017
      REPEAT_MINUTE: 1
      DB_NAME: fw_incidents

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example